version: '3'

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  php:
    extends:
      file: docker-compose.yml
      service: php
    build:
      context: ./backend/
    extra_hosts:
      - "host.docker.internal:host-gateway"

  vuejs:
    extends:
      file: docker-compose.yml
      service: vuejs

  hugo:
    extends:
      file: docker-compose.yml
      service: hugo

  db:
    extends:
      file: docker-compose.yml
      service: db

  auth:
    extends:
      file: docker-compose.yml
      service: auth
