services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  php:
    extends:
      file: docker-compose.yml
      service: php
    build:
      context: ./backend/
    pull_policy: build
    volumes:
      - ./backend/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  vuejs:
    extends:
      file: docker-compose.yml
      service: vuejs

  hugo:
    extends:
      file: docker-compose.yml
      service: hugo

  db:
    extends:
      file: docker-compose.yml
      service: db

  auth:
    extends:
      file: docker-compose.yml
      service: auth
